### PR TITLE
Make it easier to edit the gap of column-links by splitting the variables in two

### PR DESCRIPTION
**Pull request by trankten**
To prevent text overlapping in certain areas when you reduce the --gap-default value to increase menu density a new variable has been added --menu-gap-default.

This will prevent some overlapping in certain areas while allowing to modify the spacing between menu items. Tested at TKZ.One

### CODE REVIEW

**Comment by trankten** [comment]
As we discussed through Mastodon I was able to isolate the problem and this change will allow users to modify the menu density and make the menu items closers without breaking the rest of the layout by adding a new variable. 

Thank you so much for your help @ronilaukkarinen

**Comment by trankten** [comment]
Should be fine now. I hope it helps.

**Comment by ronilaukkarinen** [comment]
@trankten Which problem is this pull request trying to resolve? Can you share before and after screenshots? I'm sorry to ask this, I'm having a [postdrome](https://americanmigrainefoundation.org/resource-library/migraine-hangover/) right now and can't really focus so I'm trying to get less cognitive strain. So can you please elaborate a bit more on this, thanks.

**Comment by trankten** [comment]
> @trankten Which problem is this pull request trying to resolve? Can you share before and after screenshots? I'm sorry to ask this, I'm having a [postdrome](https://americanmigrainefoundation.org/resource-library/migraine-hangover/) right now and can't really focus so I'm trying to get less cognitive strain. So can you please elaborate a bit more on this, thanks.

Hello @ronilaukkarinen!

As we discussed through Mastodon the other day, decreasing the --gap-default value will also decrease the spacing between the text and certain areas which make it look bad.

7ba852d5a92647af

So I've separated the gap in two values (--gap-default and --menu-gap-default). The first one will control the gap in everyplace but the left side menu, which is handled by --menu-gap-default, so in case someone wants to make the menu bigger or smaller, it can be controlled using that variable without breaking the rest.

With the default --menu-default-gap (12px) the website looks like this:
imagen

But changing it to something like i.e. 6px, it will look like this, but preventing other things affected by --default-gap to missplace or break:
imagen

Thank you! 😊

**Comment by ronilaukkarinen** [comment]
Ah I'm connecting this to our discussion now. Sorry about the current state of my brain.

However, after attempting to replicate this I don't see it in the vanilla version.

This is how it is without your PR modifications:

image

This is how it is after your PR modifications: 

image

So I'm still not sure what are you trying to solve with this "Update layout-single-column.css" change? Your aim is to make it easier to edit different gaps for those who want to change them for some reason? In that case we should use default gaps everywhere like they are now with `--gap-default` and you should only separate those you'd like people to be able to edit in the future and that should use `--gap-something-else` rather other "default". Naming should be always consistent, otherwise it gets easily messy, as in `--subject-modifier-more-modifiers`.

So could you edit this to the way it uses for example `--gap-column-link`?

**Comment by trankten** [comment]
Yeah of course. I will change that later today and send the changes :)

**Comment by trankten** [comment]
I hope you get better and rest, not in a hurry for the changes anyway. Thank you so much for your time.

**Comment by trankten** [comment]
Hello.

Proposed changes have been made.

**Pull request merged**
