### PR TITLE
Change image modal slider buttons position and color

### PR DESCRIPTION
**Pull request by ChezRD**

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
Hmm, it's a bit unorthodox to use vmin and !important, why so? Gotta test it soon.

**Comment by ChezRD** [comment]
Hello!
I used those styles on my instance as hot fix:
vmin to use not a half of a screen, but somewhat of a right side of a
screen.
!important because values where forced !important elsewhere

**Comment by ChezRD** [comment]
I made some mess when I forked a repo. So i pulled your fresh version and
added two of my fixes in one commit, didn't made pull request from it though
https://github.com/ChezRD/mastodon-bird-ui/commit/454cfc0d8da87784bca2db314eb1e8d59a2893b6

**Comment by ronilaukkarinen** [comment]
You shouldn't write new styles but fix the original instead. I have now fixed this in Mastodon Bird UI, seems that modal button styles were too broad all around and leaked to wrong places. I have now disabled them completely from the Bird UI. Related issue: #42

**Pull request closed without merging**
